<?php

    class LoteDocItem
    {
        public static function add($params)
        {
            GLOBAL $dafel;

            if(!@$params->IdDocumentoItem){
                $params->IdDocumentoItem = Model::nextCode($dafel,(Object)[
                    "table" => "DocumentoItem",
                    "field" => "IdDocumentoItem",
                    "increment" => "S",
                    "base36encode" => 1
                ]);
            }

            Model::insert($dafel, (Object)[
                "table" => "LoteDocItem",
                "fields" => [
                    ["IdDocumentoItem", "s", $params->IdDocumentoItem],
                    ["IdDocumento", "s", $params->IdDocumento],
                    ["IdCFOP", "s", $params->IdCFOP],
                    ["VlPesoLiquido", "s", 0],
                    ["IdProduto", "s", $params->IdProduto],
                    ["VlUnitario", "s", $params->VlUnitario],
                    ["VlPesoBruto", "s", 0],
                    ["VlFreteRateado", "s", 0],
                    ["IdClassificacaoFiscal", "s", $params->IdClassificacaoFiscal],
                    ["VlSeguroRateado", "s", 0],
                    ["AlAcrescimoItem", "s", 0],
                    ["VlOutrasDespesasRateado", "s", 0],
                    ["TpAcrescimoItem", "s", "V"],
                    ["VlBaseIPI", "s", 0],
                    ["AlDescontoItem", "s", 0],
                    ["AlIPI", "s", 0],
                    ["QtItem", "s", $params->QtItem],
                    ["TpDescontoItem", "s", "V"],
                    ["VlIPI", "s", 0],
                    ["VlItem", "s", $params->VlItem],
                    ["VlBaseICMS", "s", $params->VlBaseICMS],
                    ["AlICMS", "s", $params->AlICMS],
                    ["VlAcrescimoItem", "s", 0],
                    ["VlDescontoItem", "s", $params->VlDescontoItem],
                    ["VlICMS", "s", $params->VlICMS],
                    ["VlBaseSubstTributaria", "s", 0],
                    ["VlAcrescimoRateado", "s", 0],
                    ["VlICMSSubstTributaria", "s", 0],
                    ["VlDescontoRateado", "s", 0],
                    ["TpEdicao", "s", @$params->TpEdicao ? $params->TpEdicao : "I"],
                    ["CdSituacaoTributaria", "s", $params->CdSituacaoTributaria],
                    ["IdSetorSaida", "s", $params->IdSetorSaida],
                    ["StEstoqueSetorEntrada", "s", "N"],
                    ["StEstoqueSetorSaida", "s", "N"],
                    ["NmEntidadeOrigem", "s", $params->NmEntidadeOrigem],
                    ["StEstoqueUnidadeDeEstoqueSaida", "s", $params->StEstoqueUnidadeDeEstoqueSaida],
                    ["IdEntidadeOrigem", "s", $params->IdEntidadeOrigem],
                    ["VlACTRateado", "s", 0],
                    ["VlBaseAdicional1", "s", 0],
                    ["VlAdicionalRateado1", "s", 0],
                    ["VlBaseAdicional2", "s", 0],
                    ["VlAdicionalRateado2", "s", 0],
                    ["VlBaseAdicional3", "s", 0],
                    ["VlAdicionalRateado3", "s", 0],
                    ["TpOrigemProduto", "s", 0],
                    ["VlBaseISS", "s", 0],
                    ["AlISS", "s", 0],
                    ["VlISS", "s", 0],
                    ["VlBaseIRRF", "s", 0],
                    ["AlIRRF", "s", 0],
                    ["VlIRRF", "s", 0],
                    ["VlBasePIS", "s", 0],
                    ["AlPIS", "s", 0],
                    ["VlPIS", "s", 0],
                    ["VlBaseCOFINS", "s", 0],
                    ["AlCOFINS", "s", 0],
                    ["VlCOFINS", "s", 0],
                    ["VlBaseCSLL", "s", 0],
                    ["AlCSLL", "s", 0],
                    ["VlCSLL", "s", 0],
                    ["VlBaseINSS", "s", 0],
                    ["AlINSS", "s", 0],
                    ["VlINSS", "s", 0],
                    ["VlBaseISSDestino", "s", 0],
                    ["AlISSDestino", "s", 0],
                    ["VlISSDestino", "s", 0],
                    ["StDesoneraICMS", "s", $params->StDesoneraICMS],
                    ["VlBaseICMSDispensado", "s", 0],
                    ["VlICMSDispensado", "s", 0],
                    ["QtEmbalagemItem", "s", 0],
                    ["VlICMSFreteRateado", "s", 0],
                    ["IdUnidade", "s", $params->IdUnidade],
                    ["VlPrecoDescontoAutomatico_A", "s", 0],
                    ["VlPISFreteRateado", "s", 0],
                    ["VlCOFINSFreteRateado", "s", 0],
                    ["StEstoqueSetorEntradaTransEmp", "s", $params->StEstoqueSetorEntradaTransEmp],
                    ["TpEntrega", "s", $params->TpEntrega],
                    ["VlUnitarioTabelaPreco", "s", $params->VlUnitario],
                    ["VlBaseII", "s", 0],
                    ["AlII", "s", 0],
                    ["VlII", "s", 0],
                    ["VlAduaneiroRateado", "s", 0],
                    ["VlDespesaAduaneiraRateado", "s", 0],
                    ["VlBaseCOFINSST", "s", 0],
                    ["AlCOFINSST", "s", 0],
                    ["VlCOFINSST", "s", 0],
                    ["VlBasePISST", "s", 0],
                    ["AlPISST", "s", 0],
                    ["VlPISST", "s", 0],
                    ["NrAdicao", "s", 0],
                    ["NrSeqItemAdicao", "s", 0],
                    ["VlDescontoItemAdicao", "s", 0],
                    ["AlCreditoICMSSN", "s", 0],
                    ["VlCreditoICMSSN", "s", 0],
                    ["CdSituacaoTributariaCOFINS", "s", 0],
                    ["CdSituacaoTributariaPIS", "s", 0],
                    ["VlDeducaoBaseISS", "s", 0],
                    ["TpDesconsideracaoItem", "s", "N"],
                    ["VlAntiDumpingRateado", "s", 0],
                    ["QtEmbalagem", "s", 0],
                    ["VlUnitarioEmbalagem", "s", 0],
                    ["VlBaseAntecipacaoICMS", "s", 0],
                    ["VlAntecipacaoICMS", "s", 0],
                    ["NrItemPedidoNFe", "s", 0],
                    ["VlBaseICMSSTInterna", "s", 0],
                    ["VlICMSSTInterna", "s", 0],
                    ["AlMVASTInterna", "s", 0],
                    ["AlICMSSTInterna", "s", 0],
                    ["AlReducaoBaseICMS", "s", 0],
                    ["AlMVA", "s", 0],
                    ["AlICMSInterna", "s", 0],
                    ["IdProduto_Empresa_FCI", "s", 0],
                    ["VlBaseICMSSTRetido", "s", 0],
                    ["VlICMSSTRetido", "s", 0],
                    ["IdHistoricoCompraICMSSTRetido", "s", 0],
                    ["VlAFRMM", "s", 0],
                    ["TpDesoneracaoICMS", "s", 0],
                    ["VlDesoneracaoICMS", "s", 0],
                    ["VlICMSOperacaoDiferimento", "s", 0],
                    ["AlDiferimentoICMS", "s", 0],
                    ["VlDiferimentoICMS", "s", 0],
                    ["VlIPIDevolucao", "s", 0],
                    ["AlPercentualDevolucaoIPI", "s", 0],
                    ["VlAliquotaPIS", "s", 0],
                    ["VlAliquotaCOFINS", "s", 0],
                    ["VlAdicionalCOFINSImportacao", "s", 0],
                    ["VlPISRetido", "s", 0],
                    ["VlCOFINSRetido", "s", 0],
                    ["VlCSLLRetido", "s", 0],
                    ["VlBaseICMSInterestadual", "s", 0],
                    ["VlBaseICMSUFDestino", "s", 0],
                    ["AlFCPUFDestino", "s", 0],
                    ["VlFCPUFDestino", "s", 0],
                    ["AlICMSUFDestino", "s", 0],
                    ["VlICMSUFDestino", "s", 0],
                    ["AlICMSInterestadual", "s", 0],
                    ["AlICMSInterestadualPartilha", "s", 0],
                    ["VlICMSUFRemetente", "s", 0],
                    ["VlJurosParcelamentoItem", "s", 0],
                    ["VlDescontoRegraComercItem", "s", 0],
                    ["QtMetragem", "s", 1],
                    ["QtDobra", "s", 0],
                    ["VlAliquotaPISST", "s", 0],
                    ["VlAliquotaCOFINSST", "s", 0],
                    ["AlReducaoBaseICMSInterestadual", "s", 0],
                    ["AlICMSComposicaoPreco", "s", 0],
                    ["VlBaseFCPUFDestino", "s", 0],
                    ["VlBaseFCP", "s", $params->VlBaseICMS],
                    ["AlFCP", "s", $params->AlFCP],
                    ["VlFCP", "s", $params->VlFCP],
                    ["VlBaseFCPSubstTributaria", "s", 0],
                    ["AlFCPSubstTributaria", "s", 0],
                    ["VlFCPSubstTributaria", "s", 0],
                    ["AlICMSSubstTributariaRetido", "s", 0],
                    ["VlBaseFCPSubstTributariaRetido", "s", 0],
                    ["AlFCPSubstTributariaRetido", "s", 0],
                    ["VlFCPSubstTributariaRetido", "s", 0],
                    ["AlReducaoBaseICMSEfetivo", "s", 0],
                    ["VlBaseICMSEfetivo", "s", 0],
                    ["AlICMSEfetivo", "s", 0],
                    ["VlICMSEfetivo", "s", 0],
                    ["VlBaseICMSRetidoSubstituto", "s", 0],
                    ["AlICMSRetidoSubstituto", "s", 0],
                    ["VlICMSRetidoSubstituto", "s", 0],
                    ["AlReducaoBaseSubstTributaria", "s", 0],
                    ["VlFreteItem", "s", 0],
                    ["TpModalidadeBaseCalculoICMSST", "s", 0],
                    ["VlICMSSTFreteRateado", "s", 0]
                ]
            ]);

            return $params->IdDocumentoItem;
        }

        public static function del($params)
        {
            GLOBAL $dafel;

            Model::delete($dafel, (Object)[
                "top" => $params->top,
                "table" => "LoteDocItem",
                "filters" => [["IdDocumento", "s", "=", $params->IdDocumento]]
            ]);
        }
    }

?>